# Generated by Django 3.2.6 on 2021-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название', max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Разборное'), (2, 'Цельное')], default=0)),
                ('manufacture', models.PositiveSmallIntegerField(choices=[(1, 'Матированное'), (1, 'Безцветное'), (1, 'Серое'), (1, 'Еще какая-то обработка')], default=0)),
                ('length', models.SmallIntegerField(default=0)),
                ('width', models.SmallIntegerField(default=0)),
                ('thickness', models.SmallIntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
