# Generated by Django 3.2.6 on 2021-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'Белый'), (2, 'Желтый'), (3, 'Синий'), (4, 'Зеленый'), (5, 'Серебрянный'), (6, 'Пурпурный'), (7, 'Розовый'), (8, 'Еще цвет'), (9, 'Или еще цвет')], default=0),
        ),
    ]
