# Generated by Django 3.2.6 on 2021-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_production_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='length',
            field=models.SmallIntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='production',
            name='thickness',
            field=models.SmallIntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='production',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='production',
            name='width',
            field=models.SmallIntegerField(default=0, help_text='mm'),
        ),
    ]
