# Generated by Django 3.2.6 on 2021-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210824_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Разборное'), (2, 'Цельное')], default=0)),
                ('manufacture', models.PositiveSmallIntegerField(choices=[(1, 'Матированное'), (1, 'Безцветное'), (1, 'Серое'), (1, 'Еще какая-то обработка')], default=0)),
                ('length', models.SmallIntegerField(default=0, help_text='mm')),
                ('width', models.SmallIntegerField(default=0, help_text='mm')),
                ('thickness', models.SmallIntegerField(default=0, help_text='mm')),
                ('color', models.SmallIntegerField(choices=[(1, 'Белый'), (2, 'Желтый'), (3, 'Синий'), (4, 'Зеленый'), (5, 'Серебрянный'), (6, 'Пурпурный'), (7, 'Розовый'), (8, 'Еще цвет'), (9, 'Или еще цвет')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='production',
            name='color',
        ),
        migrations.RemoveField(
            model_name='production',
            name='length',
        ),
        migrations.RemoveField(
            model_name='production',
            name='manufacture',
        ),
        migrations.RemoveField(
            model_name='production',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='production',
            name='type',
        ),
        migrations.RemoveField(
            model_name='production',
            name='width',
        ),
    ]
