# Generated by Django 3.2.6 on 2021-08-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210824_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='color',
            field=models.ManyToManyField(blank=True, to='core.Color'),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='manufacture',
            field=models.ManyToManyField(blank=True, to='core.Manufacture'),
        ),
    ]
