# Generated by Django 3.2.6 on 2021-08-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210825_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirror',
            old_name='length',
            new_name='height',
        ),
    ]
