# Generated by Django 3.2.6 on 2021-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_length_mirror_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='another',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
