# Generated by Django 3.2.6 on 2021-08-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210825_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirror',
            name='color',
        ),
        migrations.AddField(
            model_name='mirror',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
        migrations.RemoveField(
            model_name='mirror',
            name='manufacture',
        ),
        migrations.AddField(
            model_name='mirror',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manufacture'),
        ),
    ]
